/*
 * All course content lives here so a teacher can add or edit missions
 * without touching the game engine. kk = Kazakh, en = English, ko = Korean.
 */
const I18N = {
  kk: {
    course: "КУРС", courseTitle: "Лабиринт шебері", teacherTools: "Мұғалім құралдары",
    score: "Ұпай", lives: "Өмір", hint: "Код көмегі", run: "Іске қосу", next: "Келесі миссия",
    playGame: "Ойнау", stopGame: "Тоқтату", resumeGame: "Жалғастыру", restartGame: "Қайта бастау", resetPage: "Бетті жаңарту", resetPageConfirm: "Экран мен қазіргі ойынды жаңарту керек пе? Оқу барысы сақталады.", mission: "МИССИЯ", lesson: "САБАҚ", correct: "Дұрыс! Жаңа мүмкіндік ашылды.",
    inputMethod: "Жауап беру тәсілі", typingMode: "Бірге теру", selectMode: "Таңдау", typingGuide: "Мұғаліммен бірге сары бос орынға тер.", toolbox: "Код құралдары", toolboxHelp: "Қолдануға болатын кодтар. Бұл көмек емес!",
    wrong: "Әлі емес. Таңдауыңды қайта тексер.", selectAnswer: "Жауапты таңда", locked: "Алдыңғы миссияны аяқта.", gateTitle: "Мұғалім ашады", gateText: "Келесі тапсырмалар тобын ашу үшін мұғалім 3 таңбалы кодты енгізеді.", gateCode: "3 таңбалы код", gateUnlock: "Ашу", gateCancel: "Бас тарту", gateWrong: "Код дұрыс емес. Мұғалімнен сұра.", gateNeeded: "Дұрыс! Келесі топты мұғалім ашады.",
    skipToLesson5: "5-сабаққа бірден өту", skipConfirm: "1–4 сабақтар аяқталды деп белгіленіп, 5-сабақтан (Елесті қалпына келтіруді түзету) басталады. Жалғастыру керек пе?",
    openMapEditor: "Карта жасаушы", editorTitle: "Өз картаңды жаса", editorClear: "Тазалау", editorSave: "Сақтау және ойнау",
    editorToolWall: "Қабырға", editorToolDot: "Нүкте", editorToolPower: "Үлкен нүкте", editorToolHero: "Батыр", editorToolGhost: "Елес", editorToolErase: "Өшіру",
    editorErrorNoHero: "Алдымен батырдың бастапқы орнын қой.", editorErrorNoGhost: "Кемінде бір елес қой.", editorErrorUnreachable: "Батыр мен елес(тер) бір-біріне жете алмайды! Батыр мен барлық елес бір-біріне жүріп жете алатындай қабырғаларды қайта орналастыр.",
    editorSaved: "Карта сақталды! Енді ойнап көр.", customMapName: "Менің картам",
    allDone: "Ойын дайын!", allDoneText: "Сен лабиринт ойынын аяқтадың. Енді өз ойыныңды ойна!",
    gameOver: "Ойын аяқталды", tryAgain: "Қайта көр", win: "Жеңіс!", winText: "Барлық нүктені жинадың!", period: "БӨЛІМ", session: "СЕССИЯ", challenge: "CHALLENGE", soundOn: "Дыбыс қосулы", soundOff: "Дыбыс өшірулі", mapLabel: "Карта", ghostAI: "Елес AI", patrol: "БАРЛАУ", chase: "ҚУУ", frightened: "ҚОРҚУ", eaten: "ҮЙГЕ ОРАЛУ", pathSearch: "BFS ЖОЛ",
    mapNames: ["Классика", "Көпірлер", "Жол айрығы"],
    lessonNames: ["Қозғалыс және шарттар", "Лабиринт және ұпай", "Елес және соңғы ойын", "FSM және жол іздеу", "Елесті қалпына келтіруді түзету", "Кездейсоқ заттар", "Өз картаңды жаса"]
  },
  en: {
    course: "COURSE", courseTitle: "Maze Master", teacherTools: "Teacher tools",
    score: "Score", lives: "Lives", hint: "Code help", run: "Run", next: "Next mission",
    playGame: "Play", stopGame: "Stop", resumeGame: "Resume", restartGame: "Restart", resetPage: "Reset page", resetPageConfirm: "Reset this screen and current game? Course progress will be kept.", mission: "MISSION", lesson: "LESSON", correct: "Correct! A new feature is unlocked.",
    inputMethod: "Answer method", typingMode: "Type together", selectMode: "Choose", typingGuide: "Type in the yellow blank with your teacher.", toolbox: "Code toolbox", toolboxHelp: "Codes you may use—not a hint!",
    wrong: "Not yet. Check your choice and try again.", selectAnswer: "Choose an answer", locked: "Finish the previous mission first.", gateTitle: "Teacher unlock", gateText: "Your teacher enters the 3-digit code to open the next mission set.", gateCode: "3-digit code", gateUnlock: "Unlock", gateCancel: "Cancel", gateWrong: "That code is not correct. Ask your teacher.", gateNeeded: "Correct! Your teacher will unlock the next set.",
    skipToLesson5: "Skip to Lesson 5", skipConfirm: "Lessons 1–4 will be marked complete and you'll start Lesson 5 (Fixing the ghost respawn). Continue?",
    openMapEditor: "Map maker", editorTitle: "Design your own map", editorClear: "Clear", editorSave: "Save & play",
    editorToolWall: "Wall", editorToolDot: "Dot", editorToolPower: "Power dot", editorToolHero: "Hero", editorToolGhost: "Ghost", editorToolErase: "Erase",
    editorErrorNoHero: "Place the hero's starting tile first.", editorErrorNoGhost: "Place at least one ghost.", editorErrorUnreachable: "The hero and the ghost(s) cannot reach each other! Rearrange the walls so the hero and every ghost can walk to meet each other.",
    editorSaved: "Map saved! Try playing it.", customMapName: "My map",
    allDone: "Your game is ready!", allDoneText: "You completed the maze game. Now play your creation!",
    gameOver: "Game over", tryAgain: "Try again", win: "You win!", winText: "You collected every dot!", period: "PERIOD", session: "SESSION", challenge: "CHALLENGE", soundOn: "Sound on", soundOff: "Sound off", mapLabel: "Map", ghostAI: "Ghost AI", patrol: "PATROL", chase: "CHASE", frightened: "FRIGHTENED", eaten: "GOING HOME", pathSearch: "BFS PATH",
    mapNames: ["Classic", "Bridges", "Crossroads"],
    lessonNames: ["Movement and conditions", "Maze and score", "Ghost and final game", "FSM and path search", "Fixing the ghost respawn", "Random items", "Design your own map"]
  },
  ko: {
    course: "과정", courseTitle: "미로 게임 완성하기", teacherTools: "교사용 도구",
    score: "점수", lives: "생명", hint: "코드 도움", run: "실행", next: "다음 미션",
    playGame: "실행", stopGame: "정지", resumeGame: "계속", restartGame: "다시 시작", resetPage: "화면 초기화", resetPageConfirm: "현재 화면과 게임을 초기화할까요? 완료한 학습 진도는 유지됩니다.", mission: "미션", lesson: "차시", correct: "정답입니다! 새 기능이 열렸어요.",
    inputMethod: "답 입력 방법", typingMode: "함께 타이핑", selectMode: "보기에서 선택", typingGuide: "선생님과 함께 노란 빈칸에 직접 입력하세요.", toolbox: "코드 도구상자", toolboxHelp: "사용 가능한 코드 목록이며 힌트가 아닙니다!",
    wrong: "아직 아니에요. 선택한 답을 다시 확인해 보세요.", selectAnswer: "답 고르기", locked: "앞 미션을 먼저 완료하세요.", gateTitle: "교사 잠금 해제", gateText: "다음 문제 묶음을 열려면 선생님이 3자리 코드를 입력합니다.", gateCode: "3자리 코드", gateUnlock: "잠금 해제", gateCancel: "취소", gateWrong: "비밀번호가 맞지 않습니다.", gateNeeded: "정답입니다! 다음 묶음은 선생님이 열어 주세요.",
    skipToLesson5: "5차시로 바로 건너뛰기", skipConfirm: "1~4차시를 모두 완료 처리하고 5차시(유령 부활 고치기)부터 시작합니다. 계속할까요?",
    openMapEditor: "맵 만들기", editorTitle: "내 맵 만들기", editorClear: "지우기", editorSave: "저장하고 플레이",
    editorToolWall: "벽", editorToolDot: "점", editorToolPower: "파워 아이템", editorToolHero: "캐릭터", editorToolGhost: "유령", editorToolErase: "지우개",
    editorErrorNoHero: "먼저 캐릭터의 시작 위치를 놓아주세요.", editorErrorNoGhost: "유령을 최소 1마리 놓아주세요.", editorErrorUnreachable: "캐릭터와 유령이 서로 만날 수 없어요! 캐릭터와 모든 유령이 서로 걸어서 만날 수 있도록 벽을 다시 배치해 주세요.",
    editorSaved: "맵이 저장됐어요! 직접 플레이해 보세요.", customMapName: "내가 만든 맵",
    allDone: "게임 완성!", allDoneText: "미로 게임을 모두 완성했습니다. 이제 직접 플레이해 보세요!",
    gameOver: "게임 종료", tryAgain: "다시 하기", win: "성공!", winText: "모든 점을 모았습니다!", period: "교시", session: "세션", challenge: "CHALLENGE", soundOn: "효과음 켜짐", soundOff: "효과음 꺼짐", mapLabel: "맵", ghostAI: "유령 AI", patrol: "순찰", chase: "추적", frightened: "겁먹음", eaten: "복귀 중", pathSearch: "BFS 경로",
    mapNames: ["클래식", "다리", "교차로"],
    lessonNames: ["움직임과 조건문", "미로와 점수", "유령과 최종 게임", "FSM과 경로 탐색", "유령 부활 고치기", "무작위 아이템", "내 맵 만들기"]
  }
};

const CONCEPTS = {
  variable: { kk: "Айнымалы · Variable", en: "Variable · Айнымалы", ko: "변수 · Variable" },
  direction: { kk: "Бағыт · Direction", en: "Direction · Бағыт", ko: "방향 · Direction" },
  condition: { kk: "Шарт · Condition", en: "Condition · Шарт", ko: "조건 · Condition" },
  collision: { kk: "Соқтығыс · Collision", en: "Collision · Соқтығыс", ko: "충돌 · Collision" },
  score: { kk: "Ұпай · Score", en: "Score · Ұпай", ko: "점수 · Score" },
  boolean: { kk: "Ақиқат/Жалған · True/False", en: "True/False · Ақиқат/Жалған", ko: "참/거짓 · True/False" },
  item: { kk: "Зат · Item", en: "Item · Power-up", ko: "아이템 · Item" },
  map: { kk: "Карта · Map", en: "Map", ko: "맵 · Map" }
};

const CODE_HELP = {
  "move()": { kk: "Батырды жылжыту", en: "Move the hero", ko: "캐릭터 이동" },
  "move_up()": { kk: "Жоғары жылжыту", en: "Move up", ko: "위로 이동" },
  "move_down()": { kk: "Төмен жылжыту", en: "Move down", ko: "아래로 이동" },
  "move_right()": { kk: "Оңға жылжыту", en: "Move right", ko: "오른쪽 이동" },
  "move_left()": { kk: "Солға жылжыту", en: "Move left", ko: "왼쪽 이동" },
  "stop()": { kk: "Қозғалысты тоқтату", en: "Stop moving", ko: "이동 멈추기" },
  "score()": { kk: "Ұпайды тексеру", en: "Check score", ko: "점수 확인" },
  "add_score()": { kk: "Ұпай қосу", en: "Add score", ko: "점수 추가" },
  "hide_dot()": { kk: "Нүктені жасыру", en: "Hide a collected dot", ko: "먹은 점 숨기기" },
  "show_dot()": { kk: "Нүктені көрсету", en: "Show a dot", ko: "점 보이기" },
  "lose_life()": { kk: "Бір өмірді азайту", en: "Lose one life", ko: "생명 하나 줄이기" },
  "win()": { kk: "Жеңіс экранын ашу", en: "Show the win screen", ko: "승리 화면 열기" },
  "game_over()": { kk: "Ойынды аяқтау", en: "End the game", ko: "게임 종료하기" },
  "True": { kk: "Ақиқат / Иә", en: "True / Yes", ko: "참 / 맞음" },
  "False": { kk: "Жалған / Жоқ", en: "False / No", ko: "거짓 / 아님" },
  "==": { kk: "Тең", en: "Is equal to", ko: "서로 같다" },
  "!=": { kk: "Тең емес", en: "Is not equal to", ko: "서로 다르다" },
  "and": { kk: "Екі шарт та керек", en: "Both conditions are needed", ko: "두 조건이 모두 필요" },
  "or": { kk: "Бір шарт жеткілікті", en: "Either condition is enough", ko: "한 조건만 맞아도 됨" },
  "WALL": { kk: "Қабырға", en: "Wall", ko: "벽" },
  "DOT": { kk: "Кішкентай нүкте", en: "Small dot", ko: "작은 점" },
  "EMPTY": { kk: "Бос тор", en: "Empty cell", ko: "빈 칸" },
  "HERO": { kk: "Ойын кейіпкері", en: "Game hero", ko: "게임 캐릭터" },
  "PATROL": { kk: "Қауіпсіз аймақты барлау", en: "Patrol the maze", ko: "미로 순찰" },
  "CHASE": { kk: "Батырды қуу", en: "Chase the hero", ko: "캐릭터 추적" },
  "FRIGHTENED": { kk: "Көк және жеуге болады", en: "Blue and can be eaten", ko: "파란색이며 먹을 수 있음" },
  "QUEUE": { kk: "Алдымен кірген тор алдымен шығады", en: "First in, first out", ko: "먼저 넣은 칸부터 꺼내기" },
  "STACK": { kk: "Соңғы кірген тор алдымен шығады", en: "Last in, first out", ko: "마지막에 넣은 칸부터 꺼내기" },
  "RANDOM": { kk: "Кездейсоқ таңдау", en: "Choose randomly", ko: "무작위로 선택" },
  "NONE": { kk: "Құрылым жоқ", en: "Use no structure", ko: "자료 구조를 사용하지 않음" },
  "current": { kk: "Қазір тексеріп тұрған тор", en: "The cell being checked now", ko: "현재 확인 중인 칸" },
  "goal": { kk: "Жету керек мақсат торы", en: "The destination cell", ko: "도착해야 하는 목표 칸" },
  "wall": { kk: "Өтуге болмайтын қабырға", en: "A wall that cannot be crossed", ko: "지나갈 수 없는 벽" },
  "start": { kk: "Іздеу басталған тор", en: "The cell where search begins", ko: "탐색을 시작한 칸" },
  "enqueue(next_cell)": { kk: "Келесі торды кезекке қосу", en: "Add the next cell to the queue", ko: "다음 칸을 탐색 대기열에 추가" },
  "remove(next_cell)": { kk: "Келесі торды алып тастау", en: "Remove the next cell", ko: "다음 칸을 제거" },
  "return_path()": { kk: "Табылған жолды қайтару", en: "Return the path that was found", ko: "찾은 경로를 결과로 반환" },
  "keep_searching()": { kk: "Іздеуді жалғастыру", en: "Keep searching", ko: "탐색 계속하기" },
  "clear_queue()": { kk: "Кезекті тазалау", en: "Clear the queue", ko: "대기열 비우기" },
  "stop_ghost()": { kk: "Елесті тоқтату", en: "Stop the ghost", ko: "유령 멈추기" },
  "random_tile()": { kk: "Кездейсоқ бос торды таңдау", en: "Pick a random open tile", ko: "무작위 빈 칸 하나 고르기" },
  "fixed_start_tile()": { kk: "Әрдайым бір бастапқы тор", en: "Always the same starting tile", ko: "항상 같은 시작 칸" },
  "EATEN": { kk: "Желінді, үйге қайтуда", en: "Eaten, heading home", ko: "먹혀서 집으로 돌아가는 중" },
  "DETECTION": { kk: "Елестің байқауы", en: "Being noticed by a ghost", ko: "유령에게 들킴(감지)" },
  "COLLISION_DAMAGE": { kk: "Соқтығыс зияны", en: "Damage from touching a ghost", ko: "유령과 부딪힌 피해" },
  "SCORE": { kk: "Ұпай", en: "Score", ko: "점수" },
  "NOTHING": { kk: "Ешнәрсе", en: "Nothing", ko: "아무것도 아님" },
  "POWER": { kk: "Үлкен нүкте", en: "Power dot", ko: "파워 아이템" },
  "GHOST": { kk: "Елес", en: "Ghost", ko: "유령" },
  "show_error()": { kk: "Қате хабарын көрсету", en: "Show an error message", ko: "오류 메시지 보여주기" },
  "save_map()": { kk: "Картаны сақтау", en: "Save the map", ko: "맵 저장하기" }
};

const M = (id, originalUnit, title, instruction, concept, code, options, answer, effect, hints, teacher, input = "select") => ({
  id,
  lesson: Math.ceil(originalUnit / 2),
  block: originalUnit % 2 === 1 ? 1 : 2,
  title, instruction, concept, code, options, answer: String(answer), effect, hints, teacher, input
});

const MISSIONS = [
  M("1-1",1,{kk:"Батырды оят",en:"Wake the hero",ko:"캐릭터 깨우기"},{kk:"Ойынды бастау үшін бос орынды толтыр.",en:"Fill the blank to start the game.",ko:"빈칸을 채워 게임을 시작하세요."},"boolean","game_started = {{answer}}",["True","False"],"True","start",[{kk:"Ойын басталуы керек.",en:"The game should start.",ko:"게임이 시작되어야 해요."},{kk:"True немесе False таңда.",en:"Choose True or False.",ko:"True와 False 중 골라요."},{kk:"Жауап T әрпінен басталады.",en:"The answer begins with T.",ko:"정답은 T로 시작해요."}],""),
  M("1-2",1,{kk:"Жылдамдықты таңда",en:"Choose a speed",ko:"이동 속도 정하기"},{kk:"Батыр бір тордан жылжуы үшін санды таңда.",en:"Choose how many cells the hero moves.",ko:"캐릭터가 한 칸 이동하도록 숫자를 고르세요."},"variable","speed = {{answer}}",["0","1","5","10"],"1","speed",[{kk:"Өте үлкен сан керек емес.",en:"You do not need a large number.",ko:"큰 숫자는 필요 없어요."},{kk:"Бір торға бір саны сәйкес.",en:"One cell matches the number one.",ko:"한 칸은 숫자 1과 짝이에요."},{kk:"speed = 1",en:"speed = 1",ko:"speed = 1"}],""),
  M("1-3",1,{kk:"Оңға жылжы",en:"Move right",ko:"오른쪽으로 이동"},{kk:"Оң бағытты таңда.",en:"Choose the direction that moves right.",ko:"오른쪽 이동 방향을 고르세요."},"direction","direction = \"{{answer}}\"",["LEFT","RIGHT","UP","DOWN"],"RIGHT","right",[{kk:"→ белгісіне қара.",en:"Look at the → arrow.",ko:"→ 화살표를 보세요."},{kk:"LEFT емес, оның қарсысы.",en:"Not LEFT—choose its opposite.",ko:"LEFT의 반대말이에요."},{kk:"R____",en:"R____",ko:"R____"}],""),
  M("1-4",1,{kk:"Барлық бағыт",en:"All directions",ko:"네 방향 연결하기"},{kk:"Жоғары қозғалыс бұйрығын таңда.",en:"Choose the command for moving up.",ko:"위쪽 이동 명령을 고르세요."},"direction","if key == \"UP\":\n    {{answer}}",["move_down()","move_up()","stop()","score()"],"move_up()","directions",[{kk:"UP — жоғары.",en:"UP means жоғары.",ko:"UP은 위쪽이에요."},{kk:"move_... ішінен таңда.",en:"Choose a move_... command.",ko:"move_... 명령 중 골라요."},{kk:"move_up()",en:"move_up()",ko:"move_up()"}],""),

  M("2-1",2,{kk:"Егер оң жақ болса",en:"If the key is right",ko:"오른쪽 키 조건"},{kk:"Оң жақ пернесін тексеретін шартты толтыр.",en:"Complete the condition that checks the right key.",ko:"오른쪽 키를 확인하는 조건을 완성하세요."},"condition","if key == \"{{answer}}\":\n    move_right()",["LEFT","RIGHT","SPACE","STOP"],"RIGHT","ifRight",[{kk:"Қай перне оңға апарады?",en:"Which key goes right?",ko:"어떤 키가 오른쪽으로 갈까요?"},{kk:"LEFT пен RIGHT ішінен таңда.",en:"Choose between LEFT and RIGHT.",ko:"LEFT와 RIGHT 중 골라요."},{kk:"if key == \"RIGHT\"",en:"if key == \"RIGHT\"",ko:"if key == \"RIGHT\""}],""),
  M("2-2",2,{kk:"Тек шарт орындалса",en:"Only when true",ko:"조건이 맞을 때만"},{kk:"Команда қашан орындалатынын таңда.",en:"Choose when the command should run.",ko:"명령이 언제 실행되는지 고르세요."},"boolean","if condition == {{answer}}:\n    move()",["True","False"],"True","conditionTrue",[{kk:"Шарт дұрыс болуы керек.",en:"The condition must be correct.",ko:"조건이 맞아야 해요."},{kk:"Дұрыс = True.",en:"Correct = True.",ko:"맞다 = True예요."},{kk:"condition == True",en:"condition == True",ko:"condition == True"}],""),
  M("2-3",2,{kk:"Тоқтау шарты",en:"Stop condition",ko:"멈추는 조건"},{kk:"Қабырға алдында тоқтау үшін салыстыруды таңда.",en:"Choose the comparison that stops at a wall.",ko:"벽 앞에서 멈추는 비교를 고르세요."},"condition","if next_cell {{answer}} WALL:\n    move()",["==","!=",">","<"],"!=","notWall",[{kk:"Келесі тор қабырға болмауы керек.",en:"The next cell must not be a wall.",ko:"다음 칸이 벽이 아니어야 해요."},{kk:"!= — тең емес.",en:"!= means not equal.",ko:"!=는 같지 않다는 뜻이에요."},{kk:"next_cell != WALL",en:"next_cell != WALL",ko:"next_cell != WALL"}],""),
  M("2-4",2,{kk:"Екі шарт",en:"Two conditions",ko:"두 조건 연결"},{kk:"Ойын жүріп тұрғанда және жол ашықта қозғалу керек.",en:"Move when the game is running and the path is open.",ko:"게임 중이고 길이 열렸을 때 이동하세요."},"condition","if game_started {{answer}} path_open:\n    move()",["and","or","+","="],"and","andCondition",[{kk:"Екі шарт та керек.",en:"Both conditions are needed.",ko:"두 조건이 모두 필요해요."},{kk:"‘Және’ ағылшынша and.",en:"Және means and.",ko:"‘그리고’는 and예요."},{kk:"game_started and path_open",en:"game_started and path_open",ko:"game_started and path_open"}],""),

  M("3-1",3,{kk:"Шекараны тап",en:"Find the boundary",ko:"화면 경계 찾기"},{kk:"Сол шекарадан шықпау үшін x мәнін таңда.",en:"Choose the smallest x position.",ko:"왼쪽 경계를 넘지 않는 최소 x값을 고르세요."},"condition","if next_x >= {{answer}}:\n    move()",["0","-1","10","100"],"0","boundary",[{kk:"Торлар нөлден басталады.",en:"The grid starts at zero.",ko:"격자는 0부터 시작해요."},{kk:"Теріс санға шықпаймыз.",en:"Do not go below zero.",ko:"음수 칸으로 가지 않아요."},{kk:"next_x >= 0",en:"next_x >= 0",ko:"next_x >= 0"}],""),
  M("3-2",3,{kk:"Қабырғаны таны",en:"Recognize a wall",ko:"벽 알아보기"},{kk:"Келесі тор қабырға ма екенін тексер.",en:"Check whether the next cell is a wall.",ko:"다음 칸이 벽인지 확인하세요."},"collision","if next_cell == {{answer}}:\n    stop()",["DOT","WALL","HERO","EMPTY"],"WALL","walls",[{kk:"Қай заттан өте алмаймыз?",en:"Which object can we not pass?",ko:"무엇을 통과할 수 없나요?"},{kk:"Wall — қабырға.",en:"Wall means қабырға.",ko:"Wall은 벽이에요."},{kk:"next_cell == WALL",en:"next_cell == WALL",ko:"next_cell == WALL"}],""),
  M("3-3",3,{kk:"Ашық жол",en:"Open path",ko:"열린 길로 이동"},{kk:"Бос жолда қозғалу үшін дұрыс мәнді таңда.",en:"Choose the value that allows movement on an open path.",ko:"빈 길에서 이동하도록 값을 고르세요."},"boolean","path_open = {{answer}}",["True","False"],"True","openPath",[{kk:"Жол ашық па?",en:"Is the path open?",ko:"길이 열려 있나요?"},{kk:"Иә = True.",en:"Yes = True.",ko:"예 = True예요."},{kk:"path_open = True",en:"path_open = True",ko:"path_open = True"}],""),
  M("3-4",3,{kk:"Лабиринт дайын",en:"Build the maze",ko:"미로 완성"},{kk:"Қабырғаға соғылса, батыр не істеуі керек?",en:"What should the hero do when it hits a wall?",ko:"벽과 충돌하면 캐릭터는 어떻게 해야 할까요?"},"collision","if hit_wall:\n    {{answer}}",["move()","stop()","add_score()","win()"],"stop()","maze",[{kk:"Қабырғадан өте алмаймыз.",en:"We cannot pass through a wall.",ko:"벽은 통과할 수 없어요."},{kk:"Қозғалыстың кері әрекетін таңда.",en:"Choose the opposite of moving.",ko:"이동의 반대 동작을 골라요."},{kk:"stop()",en:"stop()",ko:"stop()"}],""),

  M("4-1",4,{kk:"Нүктені же",en:"Eat a dot",ko:"점 먹기"},{kk:"Батыр нүктеге келгенде оны жасыратын бұйрықты таңда.",en:"Choose the command that hides a collected dot.",ko:"점에 도착하면 점을 숨기는 명령을 고르세요."},"collision","if hero_position == dot_position:\n    {{answer}}",["hide_dot()","show_dot()","stop()","lose_life()"],"hide_dot()","dots",[{kk:"Жеген нүкте жоғалуы керек.",en:"A collected dot should disappear.",ko:"먹은 점은 사라져야 해요."},{kk:"hide — жасыру.",en:"Hide means жасыру.",ko:"hide는 숨기기예요."},{kk:"hide_dot()",en:"hide_dot()",ko:"hide_dot()"}],""),
  M("4-2",4,{kk:"Бір ұпай қос",en:"Add one point",ko:"점수 1점 더하기"},{kk:"Нүкте үшін бір ұпай қосатын санды таңда.",en:"Choose the number added for one dot.",ko:"점 하나를 먹을 때 더할 숫자를 고르세요."},"score","score = score + {{answer}}",["0","1","5","10"],"1","score",[{kk:"Бір нүкте — бір ұпай.",en:"One dot gives one point.",ko:"점 하나는 1점이에요."},{kk:"Қосу белгісінен кейінгі санды таңда.",en:"Choose the number after +.",ko:"+ 뒤의 숫자를 골라요."},{kk:"score = score + 1",en:"score = score + 1",ko:"score = score + 1"}],""),
  M("4-3",4,{kk:"Үлкен нүкте",en:"Power dot",ko:"파워 아이템"},{kk:"Үлкен нүкте неше ұпай береді?",en:"Choose the bonus for a power dot.",ko:"큰 점이 주는 보너스 점수를 고르세요."},"score","if dot == POWER_DOT:\n    score = score + {{answer}}",["0","1","5","100"],"5","powerDot",[{kk:"Қарапайым нүктеден көбірек.",en:"It gives more than a normal dot.",ko:"일반 점보다 더 많이 줘요."},{kk:"1-ден үлкен, 100-ден кіші.",en:"More than 1 and less than 100.",ko:"1보다 크고 100보다 작아요."},{kk:"score + 5",en:"score + 5",ko:"score + 5"}],""),
  M("4-4",4,{kk:"Жеңіс шарты",en:"Win condition",ko:"승리 조건"},{kk:"Нүкте қалмаса, жеңіс болуы үшін санды таңда.",en:"Choose the number of dots left when the player wins.",ko:"남은 점이 몇 개일 때 승리하는지 고르세요."},"condition","if dots_left == {{answer}}:\n    win()",["0","1","5","10"],"0","win",[{kk:"Бәрін жинағанда неше нүкте қалады?",en:"How many dots remain after collecting all?",ko:"모두 먹으면 몇 개가 남나요?"},{kk:"Ешбірі қалмайды.",en:"None remain.",ko:"하나도 남지 않아요."},{kk:"dots_left == 0",en:"dots_left == 0",ko:"dots_left == 0"}],""),

  M("5-1",5,{kk:"Елесті оят",en:"Wake the ghost",ko:"유령 등장"},{kk:"Елес қозғалуы үшін жылдамдықты таңда.",en:"Choose a simple speed for the ghost.",ko:"유령이 움직일 속도를 고르세요."},"variable","ghost_speed = {{answer}}",["0","1","8","20"],"1","ghost",[{kk:"0 болса, елес қозғалмайды.",en:"At zero, the ghost does not move.",ko:"0이면 유령이 움직이지 않아요."},{kk:"Баяу жылдамдықтан баста.",en:"Start with a slow speed.",ko:"느린 속도로 시작해요."},{kk:"ghost_speed = 1",en:"ghost_speed = 1",ko:"ghost_speed = 1"}],""),
  M("5-2",5,{kk:"Соқтығысты тексер",en:"Check collision",ko:"충돌 확인"},{kk:"Батыр мен елес бір орында екенін тексер.",en:"Check whether the hero and ghost share a position.",ko:"캐릭터와 유령이 같은 위치인지 확인하세요."},"collision","if hero_position {{answer}} ghost_position:\n    lose_life()",["==","!=",">","<"],"==","ghostCollision",[{kk:"Екі орын бірдей болуы керек.",en:"The two positions must be equal.",ko:"두 위치가 같아야 해요."},{kk:"Тең белгісін таңда.",en:"Choose the equals sign.",ko:"같다는 기호를 골라요."},{kk:"hero_position == ghost_position",en:"hero_position == ghost_position",ko:"hero_position == ghost_position"}],""),
  M("5-3",5,{kk:"Өмірді азайт",en:"Lose one life",ko:"생명 줄이기"},{kk:"Елеске тигенде өмірден қанша азаяды?",en:"Choose how many lives are lost on collision.",ko:"유령과 부딪히면 생명을 얼마나 줄일까요?"},"variable","lives = lives - {{answer}}",["0","1","2","10"],"1","lives",[{kk:"Бір рет соғылдық.",en:"There was one collision.",ko:"한 번 부딪혔어요."},{kk:"Бір өмір азаяды.",en:"Lose one life.",ko:"생명 하나가 줄어요."},{kk:"lives - 1",en:"lives - 1",ko:"lives - 1"}],""),
  M("5-4",5,{kk:"Ойынның соңы",en:"Game over",ko:"게임 종료 조건"},{kk:"Өмір қалмаса, ойын аяқталады. Санды таңда.",en:"The game ends when no lives remain. Choose the number.",ko:"생명이 남지 않으면 게임이 끝납니다. 숫자를 고르세요."},"condition","if lives == {{answer}}:\n    game_over()",["0","1","2","3"],"0","gameOver",[{kk:"Өмір жоқ деген неше?",en:"What number means no lives?",ko:"생명이 없다는 것은 몇 개일까요?"},{kk:"Ешбірі = 0.",en:"None = 0.",ko:"하나도 없음 = 0이에요."},{kk:"lives == 0",en:"lives == 0",ko:"lives == 0"}],""),

  M("6-1",6,{kk:"Жеңіс ережесі",en:"Complete the win rule",ko:"승리 규칙 완성"},{kk:"Барлық нүкте жиналса қандай бұйрық орындалады?",en:"Which command runs after every dot is collected?",ko:"모든 점을 먹었을 때 실행할 명령을 고르세요."},"condition","if dots_left == 0:\n    {{answer}}",["win()","stop()","lose_life()","show_dot()"],"win()","finalWin",[{kk:"Бұл жеңіс шарты.",en:"This is the win condition.",ko:"승리 조건이에요."},{kk:"Ағылшынша жеңіс — win.",en:"Жеңіс is win in English.",ko:"승리는 영어로 win이에요."},{kk:"win()",en:"win()",ko:"win()"}],""),
  M("6-2",6,{kk:"Жеңілу ережесі",en:"Complete the lose rule",ko:"패배 규칙 완성"},{kk:"Өмір нөл болса қандай бұйрық орындалады?",en:"Which command runs when lives reach zero?",ko:"생명이 0일 때 실행할 명령을 고르세요."},"condition","if lives == 0:\n    {{answer}}",["game_over()","win()","add_score()","move()"],"game_over()","finalLose",[{kk:"Бұл ойынның соңы.",en:"This ends the game.",ko:"게임이 끝나는 상황이에요."},{kk:"Game over сөзін тап.",en:"Find the words game over.",ko:"game over라는 말을 찾아요."},{kk:"game_over()",en:"game_over()",ko:"game_over()"}],""),
  M("6-3",6,{kk:"Өз ойының",en:"Customize your game",ko:"내 게임 꾸미기"},{kk:"Батырдың түсін таңда.",en:"Choose your hero's color.",ko:"캐릭터 색상을 고르세요."},"variable","hero_color = \"{{answer}}\"",["YELLOW","CYAN","PINK","GREEN"],"YELLOW","customize",[{kk:"Қалаған түсіңді таңда. Бұл миссияда бәрі дұрыс!",en:"Pick your favorite. Every choice works here!",ko:"좋아하는 색을 고르세요. 이번에는 모두 정답이에요!"},{kk:"Кез келген түсті таңда.",en:"Any color is okay.",ko:"어떤 색도 괜찮아요."},{kk:"Түсті өзің шеш.",en:"You decide the color.",ko:"스스로 색을 정해요."}],"","choice"),
  M("6-4",6,{kk:"Ойынды іске қос",en:"Launch the final game",ko:"최종 게임 실행"},{kk:"Соңғы ойынды іске қосатын мәнді таңда.",en:"Choose the value that launches the final game.",ko:"최종 게임을 실행할 값을 고르세요."},"boolean","final_game_ready = {{answer}}",["True","False"],"True","complete",[{kk:"Барлық бөлік дайын.",en:"Every part is ready.",ko:"모든 기능이 준비되었어요."},{kk:"Дайын болса — True.",en:"Ready means True.",ko:"준비되었다면 True예요."},{kk:"final_game_ready = True",en:"final_game_ready = True",ko:"final_game_ready = True"}],""),
  M("1-5",1,{kk:"★ Координата Challenge",en:"★ Coordinate Challenge",ko:"★ 좌표 이동 Challenge"},{kk:"Батырды x бағытымен дәл бір тор жылжыт.",en:"Move the hero exactly one cell on the x-axis.",ko:"캐릭터를 x축으로 정확히 한 칸 이동시키세요."},"variable","hero.x = hero.x + {{answer}}",["-1","0","1","2"],"1","coordinateStep",[{kk:"Оңға бір тор жылжимыз.",en:"Move one cell to the right.",ko:"오른쪽으로 한 칸 이동합니다."},{kk:"x мәніне оң сан қосылады.",en:"Add a positive number to x.",ko:"x에 양수를 더합니다."},{kk:"hero.x + 1",en:"hero.x + 1",ko:"hero.x + 1"}],""),
  M("2-5",2,{kk:"★ Қос шарт Challenge",en:"★ Combined Rule Challenge",ko:"★ 복합 조건 Challenge"},{kk:"Ойын басталып, RIGHT басылғанда орындалатын функцияны жаз.",en:"Choose the function that runs when the game has started and RIGHT is pressed.",ko:"게임이 시작되었고 RIGHT가 눌렸을 때 실행할 함수를 쓰세요."},"condition","if game_started and key == \"RIGHT\":\n    {{answer}}",["move_left()","move_right()","stop()","game_over()"],"move_right()","combinedRule",[{kk:"RIGHT қай бағыт?",en:"Which direction is RIGHT?",ko:"RIGHT는 어느 방향인가요?"},{kk:"move_... функциясын таңда.",en:"Choose a move_... function.",ko:"move_... 함수를 고르세요."},{kk:"move_right()",en:"move_right()",ko:"move_right()"}],""),
  M("3-5",3,{kk:"★ 2D шекара Challenge",en:"★ 2D Boundary Challenge",ko:"★ 2차원 경계 Challenge"},{kk:"15×15 картада x координатасының жоғарғы шегін толтыр.",en:"Complete the upper x boundary for a 15×15 map.",ko:"15×15 맵에서 x좌표의 위쪽 경계를 완성하세요."},"condition","if 0 <= next_x < {{answer}}:\n    move()",["0","1","14","15"],"15","bounds2d",[{kk:"Координаталар 0-ден басталады.",en:"Coordinates start at zero.",ko:"좌표는 0부터 시작합니다."},{kk:"Соңғы тор 14, бірақ шек одан бір үлкен.",en:"The final cell is 14, but the exclusive limit is one larger.",ko:"마지막 칸은 14지만 미만 조건의 경계는 하나 더 큽니다."},{kk:"0 <= next_x < 15",en:"0 <= next_x < 15",ko:"0 <= next_x < 15"}],""),
  M("4-5",4,{kk:"★ Шартты ұпай Challenge",en:"★ Conditional Score Challenge",ko:"★ 조건부 점수 Challenge"},{kk:"Power Dot болса 5, болмаса 1 ұпай беретін өрнекті аяқта.",en:"Give 5 points for a Power Dot, otherwise 1.",ko:"파워 아이템이면 5점, 아니면 1점이 되도록 완성하세요."},"score","if dot == POWER_DOT:\n    points = {{answer}}\nelse:\n    points = 1",["0","1","5","10"],"5","scoreRule",[{kk:"Power Dot кәдімгі нүктеден көп ұпай береді.",en:"A Power Dot gives more than a normal dot.",ko:"파워 아이템은 일반 점보다 점수가 큽니다."},{kk:"Кәдімгі нүкте 1, Power Dot қанша?",en:"A normal dot is 1; what is a Power Dot?",ko:"일반 점은 1점입니다. 파워 아이템은 몇 점이었나요?"},{kk:"points = 5 if ... else 1",en:"points = 5 if ... else 1",ko:"points = 5 if ... else 1"}],""),
  M("5-5",5,{kk:"★ Ghost FSM Challenge",en:"★ Ghost FSM Challenge",ko:"★ 유령 FSM Challenge"},{kk:"Қашықтық 5 немесе аз болса CHASE күйіне ауысатын шекті толтыр.",en:"Set the distance threshold that changes the ghost to CHASE.",ko:"거리가 5칸 이하일 때 CHASE 상태가 되도록 기준값을 쓰세요."},"condition","if distance <= {{answer}}:\n    ghost_state = \"CHASE\"\nelse:\n    ghost_state = \"PATROL\"",["1","3","5","10"],"5","fsmChase",[{kk:"CHASE тек жақын жерде басталады.",en:"CHASE begins only when the ghost is nearby.",ko:"CHASE는 유령이 가까울 때 시작됩니다."},{kk:"Экранда бес торлық ережені бақыла.",en:"Observe the five-cell rule on screen.",ko:"화면에서 5칸 규칙을 관찰하세요."},{kk:"distance <= 5",en:"distance <= 5",ko:"distance <= 5"}],""),
  M("6-5",6,{kk:"★ Frightened Mode Challenge",en:"★ Frightened Mode Challenge",ko:"★ 겁먹음 상태 Challenge"},{kk:"Power mode кезінде елестің түпнұсқа күй атауын жаз.",en:"Enter the original ghost state used during Power mode.",ko:"파워 모드에서 사용하는 원작의 유령 상태 이름을 쓰세요."},"condition","if power_mode:\n    ghost_state = \"{{answer}}\"",["PATROL","CHASE","FRIGHTENED","STOP"],"FRIGHTENED","frightenedAI",[{kk:"Елес көк түске өзгереді.",en:"The ghost turns blue.",ko:"유령이 파란색으로 변합니다."},{kk:"Бұл күй F әрпінен басталады.",en:"This state begins with F.",ko:"이 상태는 F로 시작합니다."},{kk:"FRIGHTENED",en:"FRIGHTENED",ko:"FRIGHTENED"}],""),

  M("7-1",7,{kk:"Бастапқы күй",en:"Choose the initial state",ko:"초기 상태 정하기"},{kk:"Ойын басталғанда елес қай күйде жүретінін таңда.",en:"Choose the ghost state used when the game begins.",ko:"게임이 시작될 때 유령이 사용할 상태를 고르세요."},"condition","ghost_state = \"{{answer}}\"",["PATROL","CHASE","FRIGHTENED","STOP"],"PATROL","fsmInitial",[{kk:"Ойын басында Power mode жоқ.",en:"Power mode is not active at the start.",ko:"게임 시작 시에는 파워 모드가 아닙니다."},{kk:"Елес алдымен лабиринтті аралайды.",en:"The ghost first moves around the maze.",ko:"유령은 먼저 미로를 순찰합니다."},{kk:"PATROL",en:"PATROL",ko:"PATROL"}],""),
  M("7-2",7,{kk:"CHASE-ке ауысу",en:"Switch to CHASE",ko:"CHASE로 전환"},{kk:"Батыр 5 тор немесе жақын болса, жаңа күйді таңда.",en:"Choose the new state when the hero is five cells away or closer.",ko:"팩맨이 5칸 이내에 있을 때 바뀔 상태를 고르세요."},"condition","if distance_to_hero <= 5:\n    ghost_state = \"{{answer}}\"",["PATROL","CHASE","FRIGHTENED","STOP"],"CHASE","fsmNear",[{kk:"Елес жақын батырды қууы керек.",en:"A nearby ghost should pursue the hero.",ko:"가까운 유령은 팩맨을 추적해야 합니다."},{kk:"Қуу күйін таңда.",en:"Choose the chasing state.",ko:"추적 상태를 고르세요."},{kk:"CHASE",en:"CHASE",ko:"CHASE"}],""),
  M("7-3",7,{kk:"Power Dot оқиғасы",en:"Handle the Power Dot event",ko:"파워 아이템 이벤트"},{kk:"Power Dot желінгенде елес ауысатын күйді таңда.",en:"Choose the state entered when a Power Dot is eaten.",ko:"파워 아이템을 먹었을 때 유령이 바뀔 상태를 고르세요."},"condition","if power_dot_eaten:\n    ghost_state = \"{{answer}}\"",["PATROL","CHASE","FRIGHTENED","STOP"],"FRIGHTENED","fsmPower",[{kk:"Бұл кезде елес көк болады.",en:"The ghost turns blue in this state.",ko:"이 상태에서는 유령이 파란색이 됩니다."},{kk:"F әрпінен басталатын күй.",en:"The state begins with F.",ko:"F로 시작하는 상태입니다."},{kk:"FRIGHTENED",en:"FRIGHTENED",ko:"FRIGHTENED"}],""),
  M("7-4",7,{kk:"Қалыпқа оралу",en:"Return after the timer",ko:"타이머 종료 후 복귀"},{kk:"Қорқу уақыты біткенде елес қай күйге оралады?",en:"Choose the state used after frightened time reaches zero.",ko:"겁먹음 시간이 0이 되면 돌아갈 상태를 고르세요."},"condition","if frightened_time == 0:\n    ghost_state = \"{{answer}}\"",["PATROL","CHASE","FRIGHTENED","STOP"],"PATROL","fsmReturn",[{kk:"Power mode енді аяқталды.",en:"Power mode has now ended.",ko:"파워 모드가 끝났습니다."},{kk:"Елес қайтадан лабиринтті аралайды.",en:"The ghost goes back to moving around the maze.",ko:"유령은 다시 미로를 순찰합니다."},{kk:"PATROL",en:"PATROL",ko:"PATROL"}],""),

  M("8-1",8,{kk:"Іздеу кезегі",en:"Choose the search queue",ko:"탐색 대기열 선택"},{kk:"BFS үшін алдымен кірген торды алдымен шығаратын құрылымды таңда.",en:"Choose the first-in, first-out structure used by BFS.",ko:"BFS에서 먼저 넣은 칸을 먼저 꺼내는 구조를 고르세요."},"variable","frontier_type = \"{{answer}}\"",["QUEUE","STACK","RANDOM","NONE"],"QUEUE","searchQueue",[{kk:"Кезекке тұрған адамдарды елестет.",en:"Think of people waiting in a line.",ko:"줄을 서서 기다리는 모습을 떠올려 보세요."},{kk:"Бірінші келген — бірінші шығады.",en:"The first one in is the first one out.",ko:"먼저 들어온 것이 먼저 나옵니다."},{kk:"QUEUE",en:"QUEUE",ko:"QUEUE"}],""),
  M("8-2",8,{kk:"Барған торларды белгіле",en:"Mark visited cells",ko:"방문한 칸 표시"},{kk:"Қазір тексерілген торды visited жиынына қос.",en:"Add the cell being checked now to the visited set.",ko:"현재 확인한 칸을 visited 집합에 추가하세요."},"variable","visited.add({{answer}})",["current","goal","wall","start"],"current","searchVisited",[{kk:"Қай торды дәл қазір тексеріп тұрмыз?",en:"Which cell are we checking right now?",ko:"지금 어떤 칸을 확인하고 있나요?"},{kk:"Оның аты current.",en:"Its name is current.",ko:"그 칸의 이름은 current입니다."},{kk:"visited.add(current)",en:"visited.add(current)",ko:"visited.add(current)"}],""),
  M("8-3",8,{kk:"Көрші торды қос",en:"Add an unvisited neighbor",ko:"방문하지 않은 이웃 추가"},{kk:"Әлі бармаған көрші торды кезекке қосатын команданы таңда.",en:"Choose the command that adds an unvisited neighbor to the queue.",ko:"아직 방문하지 않은 이웃 칸을 대기열에 넣는 명령을 고르세요."},"condition","for next_cell in neighbors(current):\n    if next_cell not in visited:\n        {{answer}}",["enqueue(next_cell)","remove(next_cell)","stop()","return_path()"],"enqueue(next_cell)","searchNeighbors",[{kk:"Кейін тексеру үшін торды сақтау керек.",en:"Save the cell so it can be checked later.",ko:"나중에 확인하도록 칸을 저장해야 합니다."},{kk:"Queue-ге қосу — enqueue.",en:"Adding to a queue is enqueue.",ko:"대기열에 추가하는 것은 enqueue입니다."},{kk:"enqueue(next_cell)",en:"enqueue(next_cell)",ko:"enqueue(next_cell)"}],""),
  M("8-4",8,{kk:"Табылған жол",en:"Return the found path",ko:"찾은 경로 반환"},{kk:"Мақсатқа жеткенде табылған жолды қайтаратын команданы таңда.",en:"Choose the command that returns the route after reaching the goal.",ko:"목표에 도착했을 때 찾은 경로를 반환하는 명령을 고르세요."},"condition","if current == goal:\n    {{answer}}",["return_path()","keep_searching()","clear_queue()","stop_ghost()"],"return_path()","searchComplete",[{kk:"Мақсат табылды, енді нәтижені береміз.",en:"The goal is found, so return the result.",ko:"목표를 찾았으므로 결과를 반환합니다."},{kk:"Жолды қайтару командасын таңда.",en:"Choose the command that returns the path.",ko:"경로를 반환하는 명령을 고르세요."},{kk:"return_path()",en:"return_path()",ko:"return_path()"}],""),
  M("9-1",9,{kk:"Кездейсоқ тірілу",en:"Random respawn",ko:"무작위 부활 위치"},{kk:"Жеп қойған елес қайда тірілуі керек? Дұрыс команданы таңда.",en:"Where should an eaten ghost respawn? Choose the right command.",ko:"먹힌 유령은 어디서 부활해야 할까요? 알맞은 명령을 고르세요."},"variable","if ghost_eaten:\n    ghost_position = {{answer}}",["fixed_start_tile()","random_tile()","hero_position","wall_tile()"],"random_tile()","ghostRespawnRandom",[{kk:"Бір орында тірілсе, дереу қайта жеуге болады.",en:"Respawning at one fixed spot lets it be eaten again right away.",ko:"한 자리에서만 부활하면 바로 다시 먹힐 수 있어요."},{kk:"Әр жолы басқа бос торды таңдайтын команданы ізде.",en:"Look for the command that picks a different open tile each time.",ko:"매번 다른 빈 칸을 고르는 명령을 찾아보세요."},{kk:"random_tile()",en:"random_tile()",ko:"random_tile()"}],""),
  M("9-2",9,{kk:"Үйге қайту",en:"Return home",ko:"집으로 돌아가기"},{kk:"Елес желінгенде қандай күйге ауысады?",en:"Which state does an eaten ghost enter?",ko:"유령이 먹히면 어떤 상태로 바뀔까요?"},"condition","if ghost_eaten:\n    ghost_state = \"{{answer}}\"",["PATROL","CHASE","FRIGHTENED","EATEN"],"EATEN","ghostRespawnHome",[{kk:"Бұл күй елес үйге қайтып жатқанын білдіреді.",en:"This state means the ghost is heading home.",ko:"이 상태는 유령이 집으로 돌아가는 중이라는 뜻이에요."},{kk:"Бұл сөз ‘жеп қойылды’ дегенді білдіреді.",en:"This word means the ghost was just eaten.",ko:"‘먹혔다’는 뜻의 단어예요."},{kk:"EATEN",en:"EATEN",ko:"EATEN"}],""),
  M("11-1",11,{kk:"Жасырыну уақыты",en:"Stealth duration",ko:"은신 지속시간"},{kk:"Жасырыну затын алғанда әсер неше секунд жалғасатынын таңда.",en:"Choose how many seconds the stealth item's effect lasts.",ko:"은신 아이템을 먹으면 효과가 몇 초 동안 지속되는지 고르세요."},"item","if item == STEALTH:\n    stealth_until = now + {{answer}}",["0","3","5","10"],"5","itemStealthDuration",[{kk:"Тым қысқа да, тым ұзақ та емес.",en:"Not too short, not too long.",ko:"너무 짧지도 길지도 않아요."},{kk:"Бес секундты ойла.",en:"Think of five seconds.",ko:"5초를 떠올려 보세요."},{kk:"stealth_until = now + 5",en:"stealth_until = now + 5",ko:"stealth_until = now + 5"}],""),
  M("11-2",11,{kk:"Елес байқамайды",en:"Ghosts can't detect you",ko:"유령이 감지 못함"},{kk:"Жасырыну кезінде елес батырды қуа ала ма?",en:"Can a ghost detect and chase the hero during stealth?",ko:"은신 중에는 유령이 캐릭터를 쫓아올 수 있을까요?"},"item","if stealth_until > now:\n    can_detect = {{answer}}",["True","False"],"False","itemStealthMechanic",[{kk:"Жасырынған батырды көру қиын.",en:"A hidden hero is hard to spot.",ko:"숨은 캐릭터는 알아보기 어려워요."},{kk:"Байқай алмаса — False.",en:"Cannot detect means False.",ko:"감지하지 못하면 False예요."},{kk:"can_detect = False",en:"can_detect = False",ko:"can_detect = False"}],""),
  M("11-3",11,{kk:"Қалқан уақыты",en:"Shield duration",ko:"방어막 지속시간"},{kk:"Қалқан затының әсер ету уақытын таңда.",en:"Choose how many seconds the shield item lasts.",ko:"방어막 아이템의 지속 시간을 고르세요."},"item","if item == PASS_THROUGH:\n    phase_until = now + {{answer}}",["0","3","5","10"],"5","itemPassThroughDuration",[{kk:"Стелс затымен бірдей уақыт.",en:"Same length as the stealth item.",ko:"은신 아이템과 같은 길이예요."},{kk:"Бес секунд.",en:"Five seconds.",ko:"5초예요."},{kk:"phase_until = now + 5",en:"phase_until = now + 5",ko:"phase_until = now + 5"}],""),
  M("11-4",11,{kk:"Соқтығыс зиян бермейді",en:"Collisions don't hurt",ko:"부딪혀도 안 다침"},{kk:"Қалқан кезінде елеске соқтығысса, өмір азая ма?",en:"Does the hero lose a life when it touches a ghost while shielded?",ko:"방어막 중에 유령과 부딪히면 생명이 줄어들까요?"},"item","if phase_until > now:\n    lose_life = {{answer}}",["True","False"],"False","itemPassThroughMechanic",[{kk:"Қалқан зиянды тоқтатады.",en:"The shield blocks the harm.",ko:"방어막이 피해를 막아줘요."},{kk:"Зиян жоқ — False.",en:"No harm means False.",ko:"피해가 없으면 False예요."},{kk:"lose_life = False",en:"lose_life = False",ko:"lose_life = False"}],""),
  M("11-5",11,{kk:"★ Стелс пен қалқан Challenge",en:"★ Stealth vs Shield Challenge",ko:"★ 은신 vs 방어막 Challenge"},{kk:"Жасырыну кезінде елеске соғылсаң да өмір азаяды, ал қалқан кезінде азаймайды. Жасырыну нені тоқтатады?",en:"Touching a ghost during stealth still costs a life, but not during the shield. What does stealth actually block?",ko:"은신 중에 유령과 부딪히면 여전히 생명이 줄지만, 방어막 중에는 줄지 않습니다. 은신이 막아주는 것은 무엇일까요?"},"item","if stealth_until > now:\n    blocks = {{answer}}",["DETECTION","COLLISION_DAMAGE","SCORE","NOTHING"],"DETECTION","itemCompareChallenge",[{kk:"Жасырыну затын қайта оқы: ол нені өзгертеді?",en:"Reread the stealth item: what does it change?",ko:"은신 아이템 설명을 다시 읽어보세요. 무엇을 바꿔주나요?"},{kk:"Стелс тек елестің байқауын тоқтатады, соқтығыс зиянын емес.",en:"Stealth only stops the ghost from noticing you, not collision damage.",ko:"은신은 유령이 알아채는 것만 막고, 부딪혔을 때의 피해는 막지 않아요."},{kk:"blocks = DETECTION",en:"blocks = DETECTION",ko:"blocks = DETECTION"}],""),
  M("11-6",11,{kk:"Баяулату уақыты",en:"Slow duration",ko:"둔화 지속시간"},{kk:"Баяулату затының әсер ету уақытын таңда.",en:"Choose how many seconds the slow item lasts.",ko:"둔화 아이템의 지속 시간을 고르세요."},"item","if item == SLOW_GHOST:\n    slow_until = now + {{answer}}",["0","3","5","10"],"5","itemSlowGhostDuration",[{kk:"Басқа заттармен бірдей.",en:"Same as the other items.",ko:"다른 아이템들과 같아요."},{kk:"Бес секунд.",en:"Five seconds.",ko:"5초예요."},{kk:"slow_until = now + 5",en:"slow_until = now + 5",ko:"slow_until = now + 5"}],""),
  M("11-7",11,{kk:"Елес жылдамдығын азайту",en:"Halve the ghost's speed",ko:"유령 속도 줄이기"},{kk:"Елес жылдамдығын жарты есеге азайтатын санды таңда.",en:"Choose the number that cuts the ghost's speed in half.",ko:"유령 속도를 절반으로 줄이는 숫자를 고르세요."},"item","if slow_until > now:\n    ghost_speed = ghost_speed * {{answer}}",["0.5","1","2","10"],"0.5","itemSlowGhostMechanic",[{kk:"Көбейткенде жылдамдық кемуі керек.",en:"Multiplying should make the speed smaller.",ko:"곱했을 때 속도가 줄어들어야 해요."},{kk:"Жарты — 0.5.",en:"Half is 0.5.",ko:"절반은 0.5예요."},{kk:"ghost_speed * 0.5",en:"ghost_speed * 0.5",ko:"ghost_speed * 0.5"}],""),
  M("11-8",11,{kk:"Жылдамдату уақыты",en:"Speed boost duration",ko:"가속 지속시간"},{kk:"Жылдамдату затының әсер ету уақытын таңда.",en:"Choose how many seconds the speed item lasts.",ko:"가속 아이템의 지속 시간을 고르세요."},"item","if item == FAST_HERO:\n    fast_until = now + {{answer}}",["0","3","5","10"],"5","itemFastHeroDuration",[{kk:"Басқа заттармен бірдей.",en:"Same as the other items.",ko:"다른 아이템들과 같아요."},{kk:"Бес секунд.",en:"Five seconds.",ko:"5초예요."},{kk:"fast_until = now + 5",en:"fast_until = now + 5",ko:"fast_until = now + 5"}],""),
  M("11-9",11,{kk:"Батыр жылдамдығын арттыру",en:"Double the hero's speed",ko:"내 속도 두 배로"},{kk:"Батыр жылдамдығын екі есе арттыратын санды таңда.",en:"Choose the number that doubles the hero's speed.",ko:"캐릭터 속도를 두 배로 만드는 숫자를 고르세요."},"item","if fast_until > now:\n    hero_speed = hero_speed * {{answer}}",["0.5","1","2","10"],"2","itemFastHeroMechanic",[{kk:"Бұл жолы жылдамдық артуы керек.",en:"This time the speed should increase.",ko:"이번엔 속도가 늘어나야 해요."},{kk:"Екі есе — 2.",en:"Double is 2.",ko:"두 배는 2예요."},{kk:"hero_speed * 2",en:"hero_speed * 2",ko:"hero_speed * 2"}],""),
  M("11-10",11,{kk:"Қабырға өту уақыты",en:"Wall-phase duration",ko:"벽 통과 지속시간"},{kk:"Қабырғадан өту затының әсер ету уақытын таңда.",en:"Choose how many seconds the wall-phase item lasts.",ko:"벽 통과 아이템의 지속 시간을 고르세요."},"item","if item == NOCLIP_WALL:\n    noclip_until = now + {{answer}}",["0","3","5","10"],"3","itemNoclipWallDuration",[{kk:"Бұл зат ең қуатты — уақыты қысқа.",en:"This item is the most powerful, so its time is short.",ko:"이 아이템은 가장 강력해서 지속시간이 짧아요."},{kk:"Үш секунд.",en:"Three seconds.",ko:"3초예요."},{kk:"noclip_until = now + 3",en:"noclip_until = now + 3",ko:"noclip_until = now + 3"}],""),
  M("11-11",11,{kk:"Қабырғадан өту",en:"Pass through walls",ko:"벽 통과 가능"},{kk:"Бұл зат кезінде батыр қабырғадан өте ала ма?",en:"Can the hero pass through walls while this item is active?",ko:"이 아이템이 활성화된 동안 캐릭터가 벽을 통과할 수 있을까요?"},"item","if noclip_until > now:\n    can_pass_wall = {{answer}}",["True","False"],"True","itemNoclipWallMechanic",[{kk:"Бұл заттың аты не туралы айтады?",en:"What does this item's name tell you?",ko:"이 아이템 이름이 무엇을 말해주나요?"},{kk:"Өте алса — True.",en:"Can pass means True.",ko:"통과할 수 있으면 True예요."},{kk:"can_pass_wall = True",en:"can_pass_wall = True",ko:"can_pass_wall = True"}],""),
  M("13-1",13,{kk:"Шекара — әрқашан қабырға",en:"The border is always a wall",ko:"테두리는 항상 벽"},{kk:"Картаның ең сыртқы шеті қандай болу керек?",en:"What should the outermost edge of the map always be?",ko:"맵의 가장 바깥쪽 테두리는 항상 무엇이어야 할까요?"},"map","border_tile = \"{{answer}}\"",["WALL","DOT","POWER","EMPTY"],"WALL","mapEditorBorder",[{kk:"Батыр шектен шығып кетпеуі керек.",en:"The hero must not be able to leave the board.",ko:"캐릭터가 맵 밖으로 나가면 안 돼요."},{kk:"Қабырға — WALL.",en:"A wall is WALL.",ko:"벽은 WALL이에요."},{kk:"border_tile = \"WALL\"",en:"border_tile = \"WALL\"",ko:"border_tile = \"WALL\""}],""),
  M("13-2",13,{kk:"Кездесу мүмкіндігін тексеру",en:"Check that they can meet",ko:"서로 만날 수 있는지 확인하기"},{kk:"Батыр мен елес бір-біріне жете алмаса, редактор не істеуі керек?",en:"If the hero and a ghost cannot reach each other, what should the editor do?",ko:"캐릭터와 유령이 서로 닿을 수 없다면 에디터는 무엇을 해야 할까요?"},"map","if not reachable(hero_start, ghost_start):\n    {{answer}}",["show_error()","save_map()","hide_dot()","win()"],"show_error()","mapEditorReachability",[{kk:"Мұндай картаны сақтауға болмайды.",en:"A map like that should not be allowed to save.",ko:"그런 맵은 저장되면 안 돼요."},{kk:"Қатені көрсету керек.",en:"An error should be shown.",ko:"오류를 보여줘야 해요."},{kk:"show_error()",en:"show_error()",ko:"show_error()"}],""),
  M("13-3",13,{kk:"Үлкен нүкте құралы",en:"Power dot tool",ko:"파워 아이템 도구"},{kk:"Редакторда орналастыруға болатын арнайы нүктенің атын таңда.",en:"Choose the name of the special dot you can place in the editor.",ko:"에디터에서 배치할 수 있는 특별한 점의 이름을 고르세요."},"map","tools.append(\"{{answer}}\")",["POWER","WALL","DOT","GHOST"],"POWER","mapEditorPowerDot",[{kk:"Бұл нүкте елесті қорқытады.",en:"This dot frightens the ghosts.",ko:"이 점은 유령을 겁먹게 만들어요."},{kk:"Үлкен нүкте — POWER.",en:"The power dot is POWER.",ko:"파워 아이템은 POWER예요."},{kk:"tools.append(\"POWER\")",en:"tools.append(\"POWER\")",ko:"tools.append(\"POWER\")"}],""),
];

MISSIONS.sort((a,b) => Number(a.id.split("-")[0]) - Number(b.id.split("-")[0]) || Number(a.id.split("-")[1]) - Number(b.id.split("-")[1]));

const LESSON_META = [
  { minutes: "50분 + 휴식 10분 + 50분", note: "1교시는 변수와 네 방향 이동, 2교시는 if와 조건을 다룹니다. 몸 활동과 짝 디버깅을 포함합니다." },
  { minutes: "50분 + 휴식 10분 + 50분", note: "1교시는 벽과 미로, 2교시는 점·점수·승리 조건을 연결합니다. 자유 미로 도전을 포함합니다." },
  { minutes: "50분 + 휴식 10분 + 50분", note: "1교시는 유령·충돌·생명, 2교시는 최종 규칙과 게임 꾸미기·발표를 진행합니다." },
  { minutes: "50분 + 휴식 10분 + 50분", note: "FSM 상태 전환 4문제와 BFS 경로 탐색 4문제를 연결합니다." },
  { minutes: "50분", note: "유령을 잡은 자리에서 바로 다시 잡혀 점수가 무한히 오르는 버그를 두 가지 방식(무작위 부활, 집으로 복귀)으로 고칩니다." },
  { minutes: "50분", note: "맵에 무작위로 등장하는 아이템 5종(은신·방어막·둔화·가속·벽 통과)의 지속시간과 효과를 완성합니다. 은신과 방어막을 비교하는 Challenge를 포함합니다." },
  { minutes: "50분", note: "맵 에디터로 벽·점·파워 아이템·캐릭터/유령 위치를 직접 배치하고, 팩맨과 유령이 서로 만날 수 있는지 자동으로 검사합니다." }
];
